# Generated by Django 3.2.15 on 2023-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pineapple', 'Ананаси'), ('apple', 'Яблука'), ('banana', 'Банани'), ('orange', 'Апельсини'), ('apricot', 'Абрикоси'), ('kiwi', 'Ківі')], max_length=9)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
